apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP
  ports:
    - name: backend-service-port
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: backend-service